### ISSUE TITLE
take 2: maybe 2016?

### ISSUE THREAD

**Issue by filtercake** [CSSunconf/CSSunconf.github.io#23]
6 months after cssconf?

sep 26 => sat mar 26 is easter => sat mar 19

**Comment by filtercake** [comment]
cc @robin-drexler

**Comment by robin-drexler** [comment]
There do not seem to any holidays and http://lanyrd.com/2016/mar/ also suggests that this might be a good date. 

Maybe, one should check if an event like cyclassics, marathon, $somethingInvolvingFireworks takes place that day.

**Comment by filtercake** [comment]
:+1: 

and as it just happened at https://github.com/nodeschool/hamburg/issues/27: is there any $soccer on that day?

**Comment by filtercake** [comment]
found [this](http://www.bundesliga.de/media/native/dokument/RTK_2015-2016.pdf):

![image](https://cloud.githubusercontent.com/assets/170145/7429384/a1d4e680-f000-11e4-96f1-cb7b65879c4d.png)

**Comment by filtercake** [comment]
doesn't look like there is a $cityBlockingEvent on that date so far: [Veranstaltungskalender Hamburg 19.03.2016](http://www.hamburg.de/tickets/ticketsuche.html?ticketSearchFrom=19.03.2016&ticketSearchTo=19.03.2016&ticketSearchGenre=69,88,60,64,53,89,83,69,51,49,71,39,50,46,52,60,64,57,58,55,56,54,61,79,104,110,78,96,73,91,121,75,108,72,77,95,98,123,122,103,99,100,76,105,94,120,106,92,90,119,97,80,102,74,93,101,109,59,35,63,68,84,70,81,87,67,62,118,82,66,65&resultlist=all)

let's give it another 7 days and if nothing else comes up against that date –> :rocket:

**Comment by robin-drexler** [comment]
:+1:
